# Generated by Django 4.2.30 on 2026-05-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("CAD", "CAD"),
                    ("AUD", "AUD"),
                    ("IRR", "IRR"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
