# Generated by Django 4.2.30 on 2026-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_alter_group_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images/"),
        ),
    ]
