# Generated by Django 4.2.30 on 2026-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_group_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="simplify_debts",
            field=models.BooleanField(default=True),
        ),
    ]
