# Generated by Django 4.2.30 on 2026-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_expense_currency_settlement_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
