# Generated by Django 4.2.30 on 2026-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_add_notes_to_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="expenses/"),
        ),
    ]
