# Generated by Django 4.2.30 on 2026-05-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_add_recurring_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
