# Generated by Django 4.2.30 on 2026-05-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_pushtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("CAD", "CAD"),
                    ("AUD", "AUD"),
                    ("JPY", "JPY"),
                    ("CHF", "CHF"),
                    ("CNY", "CNY"),
                    ("INR", "INR"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
